server:
  port: 8004
management:
  #  health:
  #    mail:
  #      enabled: false
  server:
    port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 111111


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: springcloud.entities    #所有Entity别名类所在的包


